# Generated by Django 5.1.2 on 2024-10-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('prediction_date', models.DateField()),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='stockprice',
            options={'ordering': ['-date'], 'verbose_name': 'Stock Price'},
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together={('symbol', 'date')},
        ),
        migrations.AlterModelTable(
            name='stockprice',
            table='stock_price',
        ),
    ]
