name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Navigate to project directory
        run: cd Django-Project 

      - name: Install dependencies
        run: |
          cd Django-Project  # Ensure you are in the right directory
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd Django-Project  # Ensure you are in the right directory
          source venv/bin/activate
          python manage.py test

  docker_build_push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          cd Django-Project  # Ensure Dockerfile is in the right directory
          docker build -t your-ecr-repo:latest .
      
      - name: Push Docker image to ECR
        run: |
          docker tag your-ecr-repo:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/your-ecr-repo:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/your-ecr-repo:latest

  deploy:
    needs: docker_build_push
    runs-on: ubuntu-latest

    steps:
      - name: Update ECS service
        uses: aws-actions/aws-cli-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          command: |
            aws ecs update-service --cluster your-cluster-name --service your-service-name --force-new-deployment
