name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      AWS_REGION: us-east-2  # Set the region here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          cd Django-Project/BlockhouseTest
          python -m venv venv
          source venv/bin/activate
          pip install -r ../requirements.txt

      - name: Run tests
        run: |
          cd Django-Project/BlockhouseTest
          source venv/bin/activate
          python manage.py test

  docker_build_push:
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-2  # Set the region here, too

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true
        env:
          AWS_REGION: us-east-2

      - name: Build Docker image
        run: |
          cd Django-Project 
          docker build -t curtf0505/django-web:latest .

      - name: Tag Docker image for ECR
        run: |
          docker tag curtf0505/django-web:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/curtf0505/django-web:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/curtf0505/django-web:latest

  deploy:
    needs: docker_build_push
    runs-on: ubuntu-latest

    steps:
      - name: Update ECS service
        uses: aws-actions/aws-cli-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          command: |
            aws ecs update-service --cluster BlockHouse-Cluster --service django-setup --force-new-deployment


